language: python

python:
  - "3.6"

services:
  - postgresql

before_script:
  - pip install -r requirements.txt
  - pip install coveralls codecov
  - psql -c "CREATE USER kawalya WITH PASSWORD 'kawalyaa';" -U postgres
  - psql -c 'CREATE DATABASE unstack;' -U postgres
  -  psql -c 'CREATE DATABASE unstack_test;' -U postgres

script:
  - nosetests --with-coverage --cover-package=app app/tests

after_success:
  - coveralls
  - codecov --token = QwmQE4N4fwDiOojEA0odRGAxf7GbrFfOJ
